name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.3, 8.4]
        include:
          - php: 8.3
            laravel: 11.*
            testbench: 9.*
          - php: 8.4
            laravel: 12.*
            testbench: 10.*

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Installed dependencies
        run: composer show -D

      - name: Execute tests
        run: composer test